// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fela from "reason-fela/src/Fela.bs.js";
import * as Fela$1 from "fela";
import FelaPresetWeb from "fela-preset-web";

var renderer = Fela$1.createRenderer(Fela.RendererConfig.make("reason-", undefined, undefined, undefined, undefined, FelaPresetWeb, undefined, undefined, undefined));

export {
  renderer ,
  
}
/* renderer Not a pure module */
