// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function Counter(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  return React.createElement("button", {
              onClick: (function (param) {
                  return Curry._1(setCount, (function (prevCount) {
                                return prevCount + 1 | 0;
                              }));
                })
            }, match[0]);
}

var make = Counter;

export {
  make ,
  
}
/* react Not a pure module */
