// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function DogImage(Props) {
  var imageUrl = Props.imageUrl;
  return React.createElement("img", {
              src: imageUrl
            });
}

var make = DogImage;

export {
  make ,
  
}
/* react Not a pure module */
