// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactFela from "reason-fela/src/ReactFela.bs.js";

function DogImage(Props) {
  var imageUrl = Props.imageUrl;
  var css = ReactFela.useFela1(undefined);
  return React.createElement("img", {
              className: Curry._1(css, {
                    display: "block",
                    width: "100%"
                  }),
              src: imageUrl
            });
}

var make = DogImage;

export {
  make ,
  
}
/* react Not a pure module */
