// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Counter$FunctionalVite from "./components/Counter.bs.js";
import * as ReasonReactErrorBoundary from "reason-react/src/ReasonReactErrorBoundary.bs.js";

function App(Props) {
  return React.createElement(ReasonReactErrorBoundary.make, {
              children: React.createElement("div", undefined, React.createElement("h1", undefined, "This is a counter"), React.createElement(Counter$FunctionalVite.make, {})),
              fallback: (function (param) {
                  return "Something went wrong";
                })
            });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
